const SHOP_PRODUCTS = [
  {
    id: 'panel-standard',
    category: 'panel',
    name: 'Standart Panel',
    levelLabel: 'Panel',
    price: 1200,
    productionPerSec: 8,
    description: 'Temel seviye panel. Düşük maliyetli ve stabil üretim sağlar.',
    requiredResearch: null,
  },
  {
    id: 'panel-mega',
    category: 'panel',
    name: 'Mega Panel',
    levelLabel: 'Panel',
    price: 2600,
    productionPerSec: 15,
    description: 'Gelişmiş panel. Yüksek üretim için temperli termal cam teknolojisi gerekir.',
    requiredResearch: 'temperedThermalGlass',
    requiredResearchLabel: 'Temperli Termal Cam',
  },
  {
    id: 'panel-ultra',
    category: 'panel',
    name: 'Ultra Panel',
    levelLabel: 'Panel',
    price: 4200,
    productionPerSec: 24,
    description: 'Üst segment panel. En yüksek verim için zenginleştirilmiş wafer araştırması gerekir.',
    requiredResearch: 'enrichedWafer',
    requiredResearchLabel: 'Zenginleştirilmiş Wafer',
  },
  {
    id: 'battery-lvl1',
    category: 'battery',
    name: 'Temel Depolama Ünitesi',
    levelLabel: 'Lv. 1',
    price: 900,
    capacityKwh: 200,
    description: 'Başlangıç depolama çözümü. Erken oyun için ideal.',
    requiredResearch: null,
  },
  {
    id: 'battery-lvl2',
    category: 'battery',
    name: 'Yüksek Kapasiteli Hücre',
    levelLabel: 'Lv. 2',
    price: 2200,
    capacityKwh: 420,
    description: 'Daha yüksek kapasite. İşlenmiş Kobalt araştırması sonrası açılır.',
    requiredResearch: 'processedCobalt',
    requiredResearchLabel: 'İşlenmiş Kobalt',
  },
  {
    id: 'battery-lvl3',
    category: 'battery',
    name: 'Mega Enerji İstasyonu',
    levelLabel: 'Lv. 3',
    price: 4100,
    capacityKwh: 800,
    description: 'Maksimum depolama. Süperiletken Polimer araştırması gerektirir.',
    requiredResearch: 'superconductivePolymer',
    requiredResearchLabel: 'Süperiletken Polimer',
  },
]

export default SHOP_PRODUCTS
